//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblHtml_tblPage", "tblPage", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DomainWideObjects.DataAccess.tblPage), "tblHtml", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainWideObjects.DataAccess.tblHtml), true)]

#endregion

namespace DomainWideObjects.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class seleniumScrapeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new seleniumScrapeEntities object using the connection string found in the 'seleniumScrapeEntities' section of the application configuration file.
        /// </summary>
        public seleniumScrapeEntities() : base("name=seleniumScrapeEntities", "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new seleniumScrapeEntities object.
        /// </summary>
        public seleniumScrapeEntities(string connectionString) : base(connectionString, "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new seleniumScrapeEntities object.
        /// </summary>
        public seleniumScrapeEntities(EntityConnection connection) : base(connection, "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblHtml> tblHtmls
        {
            get
            {
                if ((_tblHtmls == null))
                {
                    _tblHtmls = base.CreateObjectSet<tblHtml>("tblHtmls");
                }
                return _tblHtmls;
            }
        }
        private ObjectSet<tblHtml> _tblHtmls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblPage> tblPages
        {
            get
            {
                if ((_tblPages == null))
                {
                    _tblPages = base.CreateObjectSet<tblPage>("tblPages");
                }
                return _tblPages;
            }
        }
        private ObjectSet<tblPage> _tblPages;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblHtmls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblHtmls(tblHtml tblHtml)
        {
            base.AddObject("tblHtmls", tblHtml);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPages(tblPage tblPage)
        {
            base.AddObject("tblPages", tblPage);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblHtml")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblHtml : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblHtml object.
        /// </summary>
        /// <param name="html_id_pk">Initial value of the html_id_pk property.</param>
        public static tblHtml CreatetblHtml(global::System.Int32 html_id_pk)
        {
            tblHtml tblHtml = new tblHtml();
            tblHtml.html_id_pk = html_id_pk;
            return tblHtml;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 html_id_pk
        {
            get
            {
                return _html_id_pk;
            }
            set
            {
                if (_html_id_pk != value)
                {
                    Onhtml_id_pkChanging(value);
                    ReportPropertyChanging("html_id_pk");
                    _html_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("html_id_pk");
                    Onhtml_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _html_id_pk;
        partial void Onhtml_id_pkChanging(global::System.Int32 value);
        partial void Onhtml_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String html_data
        {
            get
            {
                return _html_data;
            }
            set
            {
                Onhtml_dataChanging(value);
                ReportPropertyChanging("html_data");
                _html_data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("html_data");
                Onhtml_dataChanged();
            }
        }
        private global::System.String _html_data;
        partial void Onhtml_dataChanging(global::System.String value);
        partial void Onhtml_dataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> page_id_fk
        {
            get
            {
                return _page_id_fk;
            }
            set
            {
                Onpage_id_fkChanging(value);
                ReportPropertyChanging("page_id_fk");
                _page_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("page_id_fk");
                Onpage_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _page_id_fk;
        partial void Onpage_id_fkChanging(Nullable<global::System.Int32> value);
        partial void Onpage_id_fkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblPage", "tblPage")]
        public tblPage tblPage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPage>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblPage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPage>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblPage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblPage> tblPageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPage>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblPage>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblPage", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPage object.
        /// </summary>
        /// <param name="page_id_pk">Initial value of the page_id_pk property.</param>
        public static tblPage CreatetblPage(global::System.Int32 page_id_pk)
        {
            tblPage tblPage = new tblPage();
            tblPage.page_id_pk = page_id_pk;
            return tblPage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 page_id_pk
        {
            get
            {
                return _page_id_pk;
            }
            set
            {
                if (_page_id_pk != value)
                {
                    Onpage_id_pkChanging(value);
                    ReportPropertyChanging("page_id_pk");
                    _page_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("page_id_pk");
                    Onpage_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _page_id_pk;
        partial void Onpage_id_pkChanging(global::System.Int32 value);
        partial void Onpage_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String page_vehicle_model
        {
            get
            {
                return _page_vehicle_model;
            }
            set
            {
                Onpage_vehicle_modelChanging(value);
                ReportPropertyChanging("page_vehicle_model");
                _page_vehicle_model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("page_vehicle_model");
                Onpage_vehicle_modelChanged();
            }
        }
        private global::System.String _page_vehicle_model;
        partial void Onpage_vehicle_modelChanging(global::System.String value);
        partial void Onpage_vehicle_modelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String page_vehicle_make
        {
            get
            {
                return _page_vehicle_make;
            }
            set
            {
                Onpage_vehicle_makeChanging(value);
                ReportPropertyChanging("page_vehicle_make");
                _page_vehicle_make = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("page_vehicle_make");
                Onpage_vehicle_makeChanged();
            }
        }
        private global::System.String _page_vehicle_make;
        partial void Onpage_vehicle_makeChanging(global::System.String value);
        partial void Onpage_vehicle_makeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblPage", "tblHtml")]
        public EntityCollection<tblHtml> tblHtmls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblHtml");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblPage", "tblHtml", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
