//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebformsUI.auction_vehicle_imageset), "auction_vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebformsUI.auction_vehicle), true)]
[assembly: EdmRelationshipAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebformsUI.auction_vehicle_model), "auction_vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebformsUI.auction_vehicle), true)]
[assembly: EdmRelationshipAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebformsUI.auction_vehicle_make), "auction_vehicle_model", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebformsUI.auction_vehicle_model), true)]

#endregion

namespace WebformsUI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuctionBaseNeoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuctionBaseNeoEntities object using the connection string found in the 'AuctionBaseNeoEntities' section of the application configuration file.
        /// </summary>
        public AuctionBaseNeoEntities() : base("name=AuctionBaseNeoEntities", "AuctionBaseNeoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuctionBaseNeoEntities object.
        /// </summary>
        public AuctionBaseNeoEntities(string connectionString) : base(connectionString, "AuctionBaseNeoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuctionBaseNeoEntities object.
        /// </summary>
        public AuctionBaseNeoEntities(EntityConnection connection) : base(connection, "AuctionBaseNeoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<auction_vehicle> auction_vehicle
        {
            get
            {
                if ((_auction_vehicle == null))
                {
                    _auction_vehicle = base.CreateObjectSet<auction_vehicle>("auction_vehicle");
                }
                return _auction_vehicle;
            }
        }
        private ObjectSet<auction_vehicle> _auction_vehicle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<auction_vehicle_imageset> auction_vehicle_imageset
        {
            get
            {
                if ((_auction_vehicle_imageset == null))
                {
                    _auction_vehicle_imageset = base.CreateObjectSet<auction_vehicle_imageset>("auction_vehicle_imageset");
                }
                return _auction_vehicle_imageset;
            }
        }
        private ObjectSet<auction_vehicle_imageset> _auction_vehicle_imageset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<auction_vehicle_make> auction_vehicle_make
        {
            get
            {
                if ((_auction_vehicle_make == null))
                {
                    _auction_vehicle_make = base.CreateObjectSet<auction_vehicle_make>("auction_vehicle_make");
                }
                return _auction_vehicle_make;
            }
        }
        private ObjectSet<auction_vehicle_make> _auction_vehicle_make;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<auction_vehicle_model> auction_vehicle_model
        {
            get
            {
                if ((_auction_vehicle_model == null))
                {
                    _auction_vehicle_model = base.CreateObjectSet<auction_vehicle_model>("auction_vehicle_model");
                }
                return _auction_vehicle_model;
            }
        }
        private ObjectSet<auction_vehicle_model> _auction_vehicle_model;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_main_with_url_local> vw_main_with_url_local
        {
            get
            {
                if ((_vw_main_with_url_local == null))
                {
                    _vw_main_with_url_local = base.CreateObjectSet<vw_main_with_url_local>("vw_main_with_url_local");
                }
                return _vw_main_with_url_local;
            }
        }
        private ObjectSet<vw_main_with_url_local> _vw_main_with_url_local;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the auction_vehicle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToauction_vehicle(auction_vehicle auction_vehicle)
        {
            base.AddObject("auction_vehicle", auction_vehicle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the auction_vehicle_imageset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToauction_vehicle_imageset(auction_vehicle_imageset auction_vehicle_imageset)
        {
            base.AddObject("auction_vehicle_imageset", auction_vehicle_imageset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the auction_vehicle_make EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToauction_vehicle_make(auction_vehicle_make auction_vehicle_make)
        {
            base.AddObject("auction_vehicle_make", auction_vehicle_make);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the auction_vehicle_model EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToauction_vehicle_model(auction_vehicle_model auction_vehicle_model)
        {
            base.AddObject("auction_vehicle_model", auction_vehicle_model);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_main_with_url_local EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_main_with_url_local(vw_main_with_url_local vw_main_with_url_local)
        {
            base.AddObject("vw_main_with_url_local", vw_main_with_url_local);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="auction_vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class auction_vehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new auction_vehicle object.
        /// </summary>
        /// <param name="auction_vehicle_id_pk">Initial value of the auction_vehicle_id_pk property.</param>
        public static auction_vehicle Createauction_vehicle(global::System.Int32 auction_vehicle_id_pk)
        {
            auction_vehicle auction_vehicle = new auction_vehicle();
            auction_vehicle.auction_vehicle_id_pk = auction_vehicle_id_pk;
            return auction_vehicle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 auction_vehicle_id_pk
        {
            get
            {
                return _auction_vehicle_id_pk;
            }
            set
            {
                if (_auction_vehicle_id_pk != value)
                {
                    Onauction_vehicle_id_pkChanging(value);
                    ReportPropertyChanging("auction_vehicle_id_pk");
                    _auction_vehicle_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("auction_vehicle_id_pk");
                    Onauction_vehicle_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _auction_vehicle_id_pk;
        partial void Onauction_vehicle_id_pkChanging(global::System.Int32 value);
        partial void Onauction_vehicle_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_auctionHouse
        {
            get
            {
                return _auction_vehicle_auctionHouse;
            }
            set
            {
                Onauction_vehicle_auctionHouseChanging(value);
                ReportPropertyChanging("auction_vehicle_auctionHouse");
                _auction_vehicle_auctionHouse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_auctionHouse");
                Onauction_vehicle_auctionHouseChanged();
            }
        }
        private global::System.String _auction_vehicle_auctionHouse;
        partial void Onauction_vehicle_auctionHouseChanging(global::System.String value);
        partial void Onauction_vehicle_auctionHouseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_lot
        {
            get
            {
                return _auction_vehicle_lot;
            }
            set
            {
                Onauction_vehicle_lotChanging(value);
                ReportPropertyChanging("auction_vehicle_lot");
                _auction_vehicle_lot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_lot");
                Onauction_vehicle_lotChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_lot;
        partial void Onauction_vehicle_lotChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_lotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_date
        {
            get
            {
                return _auction_vehicle_date;
            }
            set
            {
                Onauction_vehicle_dateChanging(value);
                ReportPropertyChanging("auction_vehicle_date");
                _auction_vehicle_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_date");
                Onauction_vehicle_dateChanged();
            }
        }
        private global::System.String _auction_vehicle_date;
        partial void Onauction_vehicle_dateChanging(global::System.String value);
        partial void Onauction_vehicle_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_year
        {
            get
            {
                return _auction_vehicle_year;
            }
            set
            {
                Onauction_vehicle_yearChanging(value);
                ReportPropertyChanging("auction_vehicle_year");
                _auction_vehicle_year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_year");
                Onauction_vehicle_yearChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_year;
        partial void Onauction_vehicle_yearChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_engine
        {
            get
            {
                return _auction_vehicle_engine;
            }
            set
            {
                Onauction_vehicle_engineChanging(value);
                ReportPropertyChanging("auction_vehicle_engine");
                _auction_vehicle_engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_engine");
                Onauction_vehicle_engineChanged();
            }
        }
        private global::System.String _auction_vehicle_engine;
        partial void Onauction_vehicle_engineChanging(global::System.String value);
        partial void Onauction_vehicle_engineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_chassis
        {
            get
            {
                return _auction_vehicle_chassis;
            }
            set
            {
                Onauction_vehicle_chassisChanging(value);
                ReportPropertyChanging("auction_vehicle_chassis");
                _auction_vehicle_chassis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_chassis");
                Onauction_vehicle_chassisChanged();
            }
        }
        private global::System.String _auction_vehicle_chassis;
        partial void Onauction_vehicle_chassisChanging(global::System.String value);
        partial void Onauction_vehicle_chassisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_equip
        {
            get
            {
                return _auction_vehicle_equip;
            }
            set
            {
                Onauction_vehicle_equipChanging(value);
                ReportPropertyChanging("auction_vehicle_equip");
                _auction_vehicle_equip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_equip");
                Onauction_vehicle_equipChanged();
            }
        }
        private global::System.String _auction_vehicle_equip;
        partial void Onauction_vehicle_equipChanging(global::System.String value);
        partial void Onauction_vehicle_equipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_mileage
        {
            get
            {
                return _auction_vehicle_mileage;
            }
            set
            {
                Onauction_vehicle_mileageChanging(value);
                ReportPropertyChanging("auction_vehicle_mileage");
                _auction_vehicle_mileage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_mileage");
                Onauction_vehicle_mileageChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_mileage;
        partial void Onauction_vehicle_mileageChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_mileageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_condition
        {
            get
            {
                return _auction_vehicle_condition;
            }
            set
            {
                Onauction_vehicle_conditionChanging(value);
                ReportPropertyChanging("auction_vehicle_condition");
                _auction_vehicle_condition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_condition");
                Onauction_vehicle_conditionChanged();
            }
        }
        private global::System.String _auction_vehicle_condition;
        partial void Onauction_vehicle_conditionChanging(global::System.String value);
        partial void Onauction_vehicle_conditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_start_bid
        {
            get
            {
                return _auction_vehicle_start_bid;
            }
            set
            {
                Onauction_vehicle_start_bidChanging(value);
                ReportPropertyChanging("auction_vehicle_start_bid");
                _auction_vehicle_start_bid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_start_bid");
                Onauction_vehicle_start_bidChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_start_bid;
        partial void Onauction_vehicle_start_bidChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_start_bidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_end_bid
        {
            get
            {
                return _auction_vehicle_end_bid;
            }
            set
            {
                Onauction_vehicle_end_bidChanging(value);
                ReportPropertyChanging("auction_vehicle_end_bid");
                _auction_vehicle_end_bid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_end_bid");
                Onauction_vehicle_end_bidChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_end_bid;
        partial void Onauction_vehicle_end_bidChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_end_bidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_status
        {
            get
            {
                return _auction_vehicle_status;
            }
            set
            {
                Onauction_vehicle_statusChanging(value);
                ReportPropertyChanging("auction_vehicle_status");
                _auction_vehicle_status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_status");
                Onauction_vehicle_statusChanged();
            }
        }
        private global::System.String _auction_vehicle_status;
        partial void Onauction_vehicle_statusChanging(global::System.String value);
        partial void Onauction_vehicle_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_model_id_fk
        {
            get
            {
                return _auction_vehicle_model_id_fk;
            }
            set
            {
                Onauction_vehicle_model_id_fkChanging(value);
                ReportPropertyChanging("auction_vehicle_model_id_fk");
                _auction_vehicle_model_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_model_id_fk");
                Onauction_vehicle_model_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_model_id_fk;
        partial void Onauction_vehicle_model_id_fkChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_model_id_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_imageset_id_fk
        {
            get
            {
                return _auction_vehicle_imageset_id_fk;
            }
            set
            {
                Onauction_vehicle_imageset_id_fkChanging(value);
                ReportPropertyChanging("auction_vehicle_imageset_id_fk");
                _auction_vehicle_imageset_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_imageset_id_fk");
                Onauction_vehicle_imageset_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_imageset_id_fk;
        partial void Onauction_vehicle_imageset_id_fkChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_imageset_id_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> auction_vehicle_scrape_date
        {
            get
            {
                return _auction_vehicle_scrape_date;
            }
            set
            {
                Onauction_vehicle_scrape_dateChanging(value);
                ReportPropertyChanging("auction_vehicle_scrape_date");
                _auction_vehicle_scrape_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_scrape_date");
                Onauction_vehicle_scrape_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _auction_vehicle_scrape_date;
        partial void Onauction_vehicle_scrape_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onauction_vehicle_scrape_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset")]
        public auction_vehicle_imageset auction_vehicle_imageset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_imageset>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_imageset>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<auction_vehicle_imageset> auction_vehicle_imagesetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_imageset>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<auction_vehicle_imageset>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle_imageset", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model")]
        public auction_vehicle_model auction_vehicle_model
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<auction_vehicle_model> auction_vehicle_modelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle_model", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="auction_vehicle_imageset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class auction_vehicle_imageset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new auction_vehicle_imageset object.
        /// </summary>
        /// <param name="imageset_id_pk">Initial value of the imageset_id_pk property.</param>
        public static auction_vehicle_imageset Createauction_vehicle_imageset(global::System.Int32 imageset_id_pk)
        {
            auction_vehicle_imageset auction_vehicle_imageset = new auction_vehicle_imageset();
            auction_vehicle_imageset.imageset_id_pk = imageset_id_pk;
            return auction_vehicle_imageset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 imageset_id_pk
        {
            get
            {
                return _imageset_id_pk;
            }
            set
            {
                if (_imageset_id_pk != value)
                {
                    Onimageset_id_pkChanging(value);
                    ReportPropertyChanging("imageset_id_pk");
                    _imageset_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("imageset_id_pk");
                    Onimageset_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _imageset_id_pk;
        partial void Onimageset_id_pkChanging(global::System.Int32 value);
        partial void Onimageset_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_local1
        {
            get
            {
                return _imageset_url_local1;
            }
            set
            {
                Onimageset_url_local1Changing(value);
                ReportPropertyChanging("imageset_url_local1");
                _imageset_url_local1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_local1");
                Onimageset_url_local1Changed();
            }
        }
        private global::System.String _imageset_url_local1;
        partial void Onimageset_url_local1Changing(global::System.String value);
        partial void Onimageset_url_local1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_local2
        {
            get
            {
                return _imageset_url_local2;
            }
            set
            {
                Onimageset_url_local2Changing(value);
                ReportPropertyChanging("imageset_url_local2");
                _imageset_url_local2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_local2");
                Onimageset_url_local2Changed();
            }
        }
        private global::System.String _imageset_url_local2;
        partial void Onimageset_url_local2Changing(global::System.String value);
        partial void Onimageset_url_local2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_local3
        {
            get
            {
                return _imageset_url_local3;
            }
            set
            {
                Onimageset_url_local3Changing(value);
                ReportPropertyChanging("imageset_url_local3");
                _imageset_url_local3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_local3");
                Onimageset_url_local3Changed();
            }
        }
        private global::System.String _imageset_url_local3;
        partial void Onimageset_url_local3Changing(global::System.String value);
        partial void Onimageset_url_local3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_remote1
        {
            get
            {
                return _imageset_url_remote1;
            }
            set
            {
                Onimageset_url_remote1Changing(value);
                ReportPropertyChanging("imageset_url_remote1");
                _imageset_url_remote1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_remote1");
                Onimageset_url_remote1Changed();
            }
        }
        private global::System.String _imageset_url_remote1;
        partial void Onimageset_url_remote1Changing(global::System.String value);
        partial void Onimageset_url_remote1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_remote2
        {
            get
            {
                return _imageset_url_remote2;
            }
            set
            {
                Onimageset_url_remote2Changing(value);
                ReportPropertyChanging("imageset_url_remote2");
                _imageset_url_remote2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_remote2");
                Onimageset_url_remote2Changed();
            }
        }
        private global::System.String _imageset_url_remote2;
        partial void Onimageset_url_remote2Changing(global::System.String value);
        partial void Onimageset_url_remote2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageset_url_remote3
        {
            get
            {
                return _imageset_url_remote3;
            }
            set
            {
                Onimageset_url_remote3Changing(value);
                ReportPropertyChanging("imageset_url_remote3");
                _imageset_url_remote3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageset_url_remote3");
                Onimageset_url_remote3Changed();
            }
        }
        private global::System.String _imageset_url_remote3;
        partial void Onimageset_url_remote3Changing(global::System.String value);
        partial void Onimageset_url_remote3Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle")]
        public EntityCollection<auction_vehicle> auction_vehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<auction_vehicle>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<auction_vehicle>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_imageset", "auction_vehicle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="auction_vehicle_make")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class auction_vehicle_make : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new auction_vehicle_make object.
        /// </summary>
        /// <param name="auction_vehicle_make_id_pk">Initial value of the auction_vehicle_make_id_pk property.</param>
        public static auction_vehicle_make Createauction_vehicle_make(global::System.Int32 auction_vehicle_make_id_pk)
        {
            auction_vehicle_make auction_vehicle_make = new auction_vehicle_make();
            auction_vehicle_make.auction_vehicle_make_id_pk = auction_vehicle_make_id_pk;
            return auction_vehicle_make;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 auction_vehicle_make_id_pk
        {
            get
            {
                return _auction_vehicle_make_id_pk;
            }
            set
            {
                if (_auction_vehicle_make_id_pk != value)
                {
                    Onauction_vehicle_make_id_pkChanging(value);
                    ReportPropertyChanging("auction_vehicle_make_id_pk");
                    _auction_vehicle_make_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("auction_vehicle_make_id_pk");
                    Onauction_vehicle_make_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _auction_vehicle_make_id_pk;
        partial void Onauction_vehicle_make_id_pkChanging(global::System.Int32 value);
        partial void Onauction_vehicle_make_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_make1
        {
            get
            {
                return _auction_vehicle_make1;
            }
            set
            {
                Onauction_vehicle_make1Changing(value);
                ReportPropertyChanging("auction_vehicle_make1");
                _auction_vehicle_make1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_make1");
                Onauction_vehicle_make1Changed();
            }
        }
        private global::System.String _auction_vehicle_make1;
        partial void Onauction_vehicle_make1Changing(global::System.String value);
        partial void Onauction_vehicle_make1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_model")]
        public EntityCollection<auction_vehicle_model> auction_vehicle_model
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_model");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<auction_vehicle_model>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_model", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="auction_vehicle_model")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class auction_vehicle_model : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new auction_vehicle_model object.
        /// </summary>
        /// <param name="auction_vehicle_model_id_pk">Initial value of the auction_vehicle_model_id_pk property.</param>
        public static auction_vehicle_model Createauction_vehicle_model(global::System.Int32 auction_vehicle_model_id_pk)
        {
            auction_vehicle_model auction_vehicle_model = new auction_vehicle_model();
            auction_vehicle_model.auction_vehicle_model_id_pk = auction_vehicle_model_id_pk;
            return auction_vehicle_model;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 auction_vehicle_model_id_pk
        {
            get
            {
                return _auction_vehicle_model_id_pk;
            }
            set
            {
                if (_auction_vehicle_model_id_pk != value)
                {
                    Onauction_vehicle_model_id_pkChanging(value);
                    ReportPropertyChanging("auction_vehicle_model_id_pk");
                    _auction_vehicle_model_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("auction_vehicle_model_id_pk");
                    Onauction_vehicle_model_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _auction_vehicle_model_id_pk;
        partial void Onauction_vehicle_model_id_pkChanging(global::System.Int32 value);
        partial void Onauction_vehicle_model_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auction_vehicle_model1
        {
            get
            {
                return _auction_vehicle_model1;
            }
            set
            {
                Onauction_vehicle_model1Changing(value);
                ReportPropertyChanging("auction_vehicle_model1");
                _auction_vehicle_model1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auction_vehicle_model1");
                Onauction_vehicle_model1Changed();
            }
        }
        private global::System.String _auction_vehicle_model1;
        partial void Onauction_vehicle_model1Changing(global::System.String value);
        partial void Onauction_vehicle_model1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auction_vehicle_make_id_fk
        {
            get
            {
                return _auction_vehicle_make_id_fk;
            }
            set
            {
                Onauction_vehicle_make_id_fkChanging(value);
                ReportPropertyChanging("auction_vehicle_make_id_fk");
                _auction_vehicle_make_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auction_vehicle_make_id_fk");
                Onauction_vehicle_make_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _auction_vehicle_make_id_fk;
        partial void Onauction_vehicle_make_id_fkChanging(Nullable<global::System.Int32> value);
        partial void Onauction_vehicle_make_id_fkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_auction_vehicle_model", "auction_vehicle")]
        public EntityCollection<auction_vehicle> auction_vehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<auction_vehicle>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<auction_vehicle>("AuctionBaseNeoModelUI.FK_auction_vehicle_auction_vehicle_model", "auction_vehicle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AuctionBaseNeoModelUI", "FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make")]
        public auction_vehicle_make auction_vehicle_make
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_make>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_make>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<auction_vehicle_make> auction_vehicle_makeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<auction_vehicle_make>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<auction_vehicle_make>("AuctionBaseNeoModelUI.FK_auction_vehicle_model_auction_vehicle_make", "auction_vehicle_make", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuctionBaseNeoModelUI", Name="vw_main_with_url_local")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_main_with_url_local : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_main_with_url_local object.
        /// </summary>
        /// <param name="id_pk">Initial value of the id_pk property.</param>
        public static vw_main_with_url_local Createvw_main_with_url_local(global::System.Int32 id_pk)
        {
            vw_main_with_url_local vw_main_with_url_local = new vw_main_with_url_local();
            vw_main_with_url_local.id_pk = id_pk;
            return vw_main_with_url_local;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_pk
        {
            get
            {
                return _id_pk;
            }
            set
            {
                if (_id_pk != value)
                {
                    Onid_pkChanging(value);
                    ReportPropertyChanging("id_pk");
                    _id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_pk");
                    Onid_pkChanged();
                }
            }
        }
        private global::System.Int32 _id_pk;
        partial void Onid_pkChanging(global::System.Int32 value);
        partial void Onid_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String make
        {
            get
            {
                return _make;
            }
            set
            {
                OnmakeChanging(value);
                ReportPropertyChanging("make");
                _make = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("make");
                OnmakeChanged();
            }
        }
        private global::System.String _make;
        partial void OnmakeChanging(global::System.String value);
        partial void OnmakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lot
        {
            get
            {
                return _lot;
            }
            set
            {
                OnlotChanging(value);
                ReportPropertyChanging("lot");
                _lot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lot");
                OnlotChanged();
            }
        }
        private Nullable<global::System.Int32> _lot;
        partial void OnlotChanging(Nullable<global::System.Int32> value);
        partial void OnlotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private Nullable<global::System.Int32> _year;
        partial void OnyearChanging(Nullable<global::System.Int32> value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String engine
        {
            get
            {
                return _engine;
            }
            set
            {
                OnengineChanging(value);
                ReportPropertyChanging("engine");
                _engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("engine");
                OnengineChanged();
            }
        }
        private global::System.String _engine;
        partial void OnengineChanging(global::System.String value);
        partial void OnengineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String chassis
        {
            get
            {
                return _chassis;
            }
            set
            {
                OnchassisChanging(value);
                ReportPropertyChanging("chassis");
                _chassis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("chassis");
                OnchassisChanged();
            }
        }
        private global::System.String _chassis;
        partial void OnchassisChanging(global::System.String value);
        partial void OnchassisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String equip
        {
            get
            {
                return _equip;
            }
            set
            {
                OnequipChanging(value);
                ReportPropertyChanging("equip");
                _equip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("equip");
                OnequipChanged();
            }
        }
        private global::System.String _equip;
        partial void OnequipChanging(global::System.String value);
        partial void OnequipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mileage
        {
            get
            {
                return _mileage;
            }
            set
            {
                OnmileageChanging(value);
                ReportPropertyChanging("mileage");
                _mileage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mileage");
                OnmileageChanged();
            }
        }
        private Nullable<global::System.Int32> _mileage;
        partial void OnmileageChanging(Nullable<global::System.Int32> value);
        partial void OnmileageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String condition
        {
            get
            {
                return _condition;
            }
            set
            {
                OnconditionChanging(value);
                ReportPropertyChanging("condition");
                _condition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("condition");
                OnconditionChanged();
            }
        }
        private global::System.String _condition;
        partial void OnconditionChanging(global::System.String value);
        partial void OnconditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> startbid
        {
            get
            {
                return _startbid;
            }
            set
            {
                OnstartbidChanging(value);
                ReportPropertyChanging("startbid");
                _startbid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startbid");
                OnstartbidChanged();
            }
        }
        private Nullable<global::System.Int32> _startbid;
        partial void OnstartbidChanging(Nullable<global::System.Int32> value);
        partial void OnstartbidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> endbid
        {
            get
            {
                return _endbid;
            }
            set
            {
                OnendbidChanging(value);
                ReportPropertyChanging("endbid");
                _endbid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endbid");
                OnendbidChanged();
            }
        }
        private Nullable<global::System.Int32> _endbid;
        partial void OnendbidChanging(Nullable<global::System.Int32> value);
        partial void OnendbidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String localurl1
        {
            get
            {
                return _localurl1;
            }
            set
            {
                Onlocalurl1Changing(value);
                ReportPropertyChanging("localurl1");
                _localurl1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("localurl1");
                Onlocalurl1Changed();
            }
        }
        private global::System.String _localurl1;
        partial void Onlocalurl1Changing(global::System.String value);
        partial void Onlocalurl1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String localurl2
        {
            get
            {
                return _localurl2;
            }
            set
            {
                Onlocalurl2Changing(value);
                ReportPropertyChanging("localurl2");
                _localurl2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("localurl2");
                Onlocalurl2Changed();
            }
        }
        private global::System.String _localurl2;
        partial void Onlocalurl2Changing(global::System.String value);
        partial void Onlocalurl2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String localurl3
        {
            get
            {
                return _localurl3;
            }
            set
            {
                Onlocalurl3Changing(value);
                ReportPropertyChanging("localurl3");
                _localurl3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("localurl3");
                Onlocalurl3Changed();
            }
        }
        private global::System.String _localurl3;
        partial void Onlocalurl3Changing(global::System.String value);
        partial void Onlocalurl3Changed();

        #endregion
    
    }

    #endregion
    
}
